#!/usr/bin/env bash
# Report how far the current branch lags/leads upstream/main.
# Generated by fork-maintenance-flow-builder for
# obsidian-pivi-cross.
#
# This is the fork's *disturbance error signal*: behind = how stale the branch
# is relative to upstream, ahead = how many custom commits sit on top. Run it
# any time you want a quick sync-health reading without a full rebase.
#
# Usage:  ./.fork-skills/upstream-status.sh [upstream-branch]
#   upstream-branch defaults to "main"
set -euo pipefail

UPSTREAM_REMOTE="upstream"
UPSTREAM_BRANCH="${1:-main}"
UPSTREAM_REF="${UPSTREAM_REMOTE}/${UPSTREAM_BRANCH}"

# Ensure the upstream remote exists.
if ! git remote get-url "$UPSTREAM_REMOTE" &>/dev/null; then
  echo "error: remote '${UPSTREAM_REMOTE}' is not configured" >&2
  echo "       add it with: git remote add ${UPSTREAM_REMOTE} <upstream-url>" >&2
  exit 1
fi

# Fetch latest upstream refs (quiet, non-fatal on offline).
git fetch "$UPSTREAM_REMOTE" --quiet 2>/dev/null || {
  echo "warning: could not fetch '${UPSTREAM_REMOTE}', using last-known refs" >&2
}

# Resolve upstream branch.
if ! git rev-parse --verify --quiet "$UPSTREAM_REF" >/dev/null; then
  echo "error: upstream branch '${UPSTREAM_REF}' not found" >&2
  exit 1
fi

CURRENT_BRANCH="$(git branch --show-current)"
BEHIND="$(git rev-list --count HEAD.."$UPSTREAM_REF" 2>/dev/null || echo "?")"
AHEAD="$(git rev-list --count "$UPSTREAM_REF"..HEAD 2>/dev/null || echo "?")"

echo "branch:    ${CURRENT_BRANCH}"
echo "upstream:  ${UPSTREAM_REF}"
echo "behind:    ${BEHIND} commit(s)"
echo "ahead:     ${AHEAD} commit(s)"
